# <center>Reinforcement learning using Q-learning</center>

---
### <center><font color="blue">Content</font></center>
[Introduction](#Introduction)

[Terminology](#Terminology)

[Path problem solution using Q learning](#Path-problem-solution-using-Q-learning)

[References](#References:) 

---

## Introduction

`Machine learning` is a subset of artificial intelligence which provides machines the ability to learn automatically and improve from experience without being explicily programmed.

`Reinforcement learning`(RL) is a type of machine learning where an agent learns to behave in a environment by performing actions and seeing the results.

<center><IMG src="https://www.kdnuggets.com/images/reinforcement-learning-fig1-700.jpg" width="500"/></center>

The following parameters are need ti attain a solution
- Set of action,A
- Set of states,S
- Rewards,R
- Policy,${\pi}$
- Value,V

### Terminology

`Agent`: The RL algorithm that learns from trail and error.

`Environment`: The world through which the agent moves.

`Action`(A): All the possible steps that the agent can take.

`State`(S): Current condition returned by the environment.

`Reward`(R): An instant return from the environment to appraise the last action.

`Policy`(${\pi}$): The approach that the agent uses to determine the next action based on the current state.

`Value` (V): The expected long-term return with discount, as opposed to the short-term reward R.

`Action-value`(Q): This is similar to value expected, it takes an extra parameter, the current action(A).

`Exploitation`: It is about using the already known exploited information to heighten the reward.

`Exploration`: It is about exploring and capturing more information about an environment.

`Markov Decision process`: The mathematical approach for mapping a solution in RL.

## Path problem solution using Q learning

**Problem**: Example describes an agent which uses unsupervised training to learn about an unknown environment. Suppose we have 5 rooms in a building connected by doors as shown in the figure below.  We'll number each room 0 through 4.  The outside of the building can be thought of as one big room (5). Find the best path to go out of room 2 to 5.

<center><IMG src="http://mnemstudio.org/ai/path/images/modeling_environment_clip_image002a.gif" width="500"/></center>

---
**Algorithm**
- Set the gamma parameter, and environment rewards in matrix,R
- Initialize matrix Q to zero
- Select a random initial state
- Set initial state = current state
- Select one among all possible actions for the current state
- Using this possible action, consider going to next state
- Get maximum Q value for this next state based on all possible actions
- Compute <center>$Q(State, Action)=R(State, Action)+gamma*max[Q(next\;state, all\;action)]$</center>
---

The algorithm above is used by the agent to learn from experience.  Each episode is equivalent to one training session.  In each training session, the agent explores the environment (represented by matrix R ), receives the reward (if any) until it reaches the goal state. The purpose of the training is to enhance the 'brain' of our agent, represented by matrix Q.  More training results in a more optimized matrix Q.  In this case, if the matrix Q has been enhanced, instead of exploring around, and going back and forth to the same rooms, the agent will find the fastest route to the goal state.

The Gamma parameter has a range of 0 to 1 (0 <= Gamma < 1).  If Gamma is closer to zero, the agent will tend to consider only immediate rewards.  If Gamma is closer to one, the agent will consider future rewards with greater weight, willing to delay the reward.

- Room is State.

- Agent movement from one room to another represents an action.

**Reward distribution**

We can represent the rooms on a graph, each room as a node, and each door as a link.

<center><IMG src="http://mnemstudio.org/ai/path/images/map3a.gif" width="500"/></center>

For this example, we'd like to put an agent in any room, and from that room, go outside the building (this will be our target room). In other words, the goal room is number 5. To set this room as a goal, we'll associate a reward value to each door (i.e. link between nodes). The doors that lead immediately to the goal have an instant reward of 100.  Other doors not directly connected to the target room have zero reward. Because doors are two-way ( 0 leads to 4, and 4 leads back to 0 ), two arrows are assigned to each room. Room 5 loops back to itself with a reward of 100, and all other direct connections to the goal room carry a reward of 100.  In Q-learning, the goal is to reach the state with the highest reward, so that if the agent arrives at the goal, it will remain there forever. This type of goal is called an "absorbing goal".

In [3]:
import numpy as np

<center><img src="http://mnemstudio.org/ai/path/images/r_matrix1.gif" width="300"/></center>

In [4]:
# R matrix
R=np.matrix([[-1,-1,-1,-1,0,-1],
             [-1,-1,-1,0,-1,100],
             [-1,-1,-1,0,-1,-1],
             [-1,0,0,-1,0,-1],
             [-1,0,0,-1,-1,100],
             [-1,0,-1,-1,0,100]])

In [5]:
#Q matrix
Q=np.matrix(np.zeros([6,6]))

In [6]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [7]:
# Gamma (learning parameter)
gamma=0.8

In [69]:
# Initial state (usually to be chosen at random)
initial_state=1

In [70]:
# This function returns all available actions in the state give as an argument
def available_actions(state):
    current_state_row=R[state,]
    av_act=np.where(current_state_row>=0)[1]
    return av_act

In [71]:
# Get available actions in the current state
available_act=available_actions(initial_state)
available_act

array([3, 5], dtype=int64)

In [76]:
# This function chooses at random which action to be performed within the range of all the available action
def sample_next_action(available_action_range):
    next_action=int(np.random.choice(available_act,1))
    return next_action

In [77]:
# Sample next action to be performed
action=sample_next_action(available_act)
action

5

In [78]:
#This function updates the Q matrix according to the path selected and the Q learning algorithm
def update(current_state,action,gamma):
    max_index=np.where(Q[action,]==np.max(Q[action,]))[1]
    if max_index.shape[0]>1:
        max_index=int(np.random.choice(max_index,size=1))
    else:
        max_index=int(max_index)
    max_value=Q[action,max_index]
    # Q learning formula
    Q[current_state,action]=R[current_state,action]+gamma*max_value

In [79]:
# Update Q matrix
update(initial_state,action,gamma)

In [80]:
Q

matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,   0.,   0., 320.,   0., 500.],
        [  0.,   0.,   0., 320.,   0.,   0.],
        [  0., 400., 256.,   0., 400.,   0.],
        [  0., 400., 256.,   0.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])

In [81]:
# Training
# Train over 10,OOO iterations. [Re-iterate the process above]
for i in range(10000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    available_act=available_actions(current_state)
    action=sample_next_action(available_act)
    update(current_state,action,gamma)

In [82]:
# Normalize the "trained" Q matrix
print("Trained Q matrix:")
print(Q/np.max(Q)*100)

Trained Q matrix:
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


In [83]:
# Testing
# Goal state=5
# Best sequence path starting from 2->1,3,1,5
current_state=2
steps=[current_state]
while current_state!=5:
    next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    if next_step_index.shape[0]>1:
        next_step_index=int(np.random.choice(next_step_index,size=1))
    else:
        next_step_index=int(next_step_index)
    steps.append(next_step_index)
    current_state=next_step_index
# Print selected sequence of steps
print("Selected path:")
print(steps)

Selected path:
[2, 3, 1, 5]


<center><IMG src="http://mnemstudio.org/ai/path/images/modeling_environment_clip_image002a.gif" width="300"/></center>

## References:

[edureka!][]

[Q-learning][]

[Q-learning]:http://mnemstudio.org/path-finding-q-learning-tutorial.htm
[edureka!]:https://www.youtube.com/watch?v=LzaWrmKL1Z4